const roomCards = [
  {
    roomNumber: 888,
    price: 9990,
    isLux: true,
    reviewsCount: 145,
    imgsSrc: [
      `${require('../assets/img/rooms/room-1.jpg')}`,
      `${require('../assets/img/rooms/room-1.jpg')}`,
      `${require('../assets/img/rooms/room-1.jpg')}`,
      `${require('../assets/img/rooms/room-1.jpg')}`,
    ],
    rateNumber: 5,
  },
  {
    roomNumber: 840,
    price: 9990,
    reviewsCount: 64,
    imgsSrc: [
      `${require('../assets/img/rooms/room-2.jpg')}`,
      `${require('../assets/img/rooms/room-2.jpg')}`,
      `${require('../assets/img/rooms/room-2.jpg')}`,
      `${require('../assets/img/rooms/room-2.jpg')}`,
    ],
    rateNumber: 4,
  },
  {
    roomNumber: 980,
    price: 8500,
    isLux: true,
    reviewsCount: 35,
    imgsSrc: [
      `${require('../assets/img/rooms/room-3.jpg')}`,
      `${require('../assets/img/rooms/room-3.jpg')}`,
      `${require('../assets/img/rooms/room-3.jpg')}`,
      `${require('../assets/img/rooms/room-3.jpg')}`,
    ],
    rateNumber: 3,
  },
  {
    roomNumber: 856,
    price: 7300,
    reviewsCount: 19,
    imgsSrc: [
      `${require('../assets/img/rooms/room-4.jpg')}`,
      `${require('../assets/img/rooms/room-4.jpg')}`,
      `${require('../assets/img/rooms/room-4.jpg')}`,
      `${require('../assets/img/rooms/room-4.jpg')}`,
    ],
    rateNumber: 5,
  },
  {
    roomNumber: 740,
    price: 6000,
    reviewsCount: 44,
    imgsSrc: [
      `${require('../assets/img/rooms/room-5.jpg')}`,
      `${require('../assets/img/rooms/room-5.jpg')}`,
      `${require('../assets/img/rooms/room-5.jpg')}`,
      `${require('../assets/img/rooms/room-5.jpg')}`,
    ],
    rateNumber: 4,
  },
  {
    roomNumber: 982,
    price: 5800,
    reviewsCount: 56,
    imgsSrc: [
      `${require('../assets/img/rooms/room-6.jpg')}`,
      `${require('../assets/img/rooms/room-6.jpg')}`,
      `${require('../assets/img/rooms/room-6.jpg')}`,
      `${require('../assets/img/rooms/room-6.jpg')}`,
    ],
    rateNumber: 3,
  },
  {
    roomNumber: 678,
    price: 5550,
    reviewsCount: 45,
    imgsSrc: [
      `${require('../assets/img/rooms/room-7.jpg')}`,
      `${require('../assets/img/rooms/room-7.jpg')}`,
      `${require('../assets/img/rooms/room-7.jpg')}`,
      `${require('../assets/img/rooms/room-7.jpg')}`,
    ],
    rateNumber: 5,
  },
  {
    roomNumber: 450,
    price: 5300,
    reviewsCount: 39,
    imgsSrc: [
      `${require('../assets/img/rooms/room-8.jpg')}`,
      `${require('../assets/img/rooms/room-8.jpg')}`,
      `${require('../assets/img/rooms/room-8.jpg')}`,
      `${require('../assets/img/rooms/room-8.jpg')}`,
    ],
    rateNumber: 4,
  },
  {
    roomNumber: 350,
    price: 5000,
    reviewsCount: 77,
    imgsSrc: [
      `${require('../assets/img/rooms/room-9.jpg')}`,
      `${require('../assets/img/rooms/room-9.jpg')}`,
      `${require('../assets/img/rooms/room-9.jpg')}`,
      `${require('../assets/img/rooms/room-9.jpg')}`,
    ],
    rateNumber: 3,
  },
  {
    roomNumber: 666,
    price: '5000',
    reviewsCount: 25,
    imgsSrc: [
      `${require('../assets/img/rooms/room-10.jpg')}`,
      `${require('../assets/img/rooms/room-10.jpg')}`,
      `${require('../assets/img/rooms/room-10.jpg')}`,
      `${require('../assets/img/rooms/room-10.jpg')}`,
    ],
    rateNumber: 5,
  },
  {
    roomNumber: 444,
    price: 5000,
    reviewsCount: 15,
    imgsSrc: [
      `${require('../assets/img/rooms/room-11.jpg')}`,
      `${require('../assets/img/rooms/room-11.jpg')}`,
      `${require('../assets/img/rooms/room-11.jpg')}`,
      `${require('../assets/img/rooms/room-11.jpg')}`,
    ],
    rateNumber: 3,
  },
  {
    roomNumber: 352,
    price: 5000,
    reviewsCount: 55,
    imgsSrc: [
      `${require('../assets/img/rooms/room-12.jpg')}`,
      `${require('../assets/img/rooms/room-12.jpg')}`,
      `${require('../assets/img/rooms/room-12.jpg')}`,
      `${require('../assets/img/rooms/room-12.jpg')}`,
    ],
    rateNumber: 3,
  },
];

export { roomCards };
